### ISSUE TITLE
[Bug] Mongo can't be connected 

### ISSUE THREAD

**Issue by Jiancong** [growthbook/growthbook#2346] opened 2024-04-05 02:35 UTC
### Summary
I've setup a self-host instance in my machine with a mongo run in 27017

root@es-node-1:~/src/growthbook# lsof -i :27017
COMMAND    PID    USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
mongod  777075 mongodb   11u  IPv4 1008701957      0t0  TCP localhost:27017 (LISTEN)

And this is my docker-compose.yml. Unfortunately, I only get Mongo connection refused.

version: "3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_USERNAME=ana
      - MONGO_INITDB_PASSWORD=ana
      - MONGO_HOST=127.0.0.1
      - MONGO_DBNAME=aidesigns
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://ana:ana@127.0.0.1:27017/aidesigns?authSource=admin
      - APP_ORIGIN=http://127.0.0.1:3000
      - API_HOST=http://127.0.0.1:3100
      - NODE_ENV=production
      - JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ==.bm90X2ltcGxlbWVudGVk
      - ENCRYPTION_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ==.bm90X2ltcGxlbWVudGVk
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
  mongodata:

#### Expected Behavior
The mongo should be connected.

#### Current Behavior

growthbook_1  | (node:65) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
growthbook_1  | (Use `node --trace-deprecation ...` to show where the warning was created)
growthbook_1  | {"level":30,"time":1712283948978,"pid":65,"hostname":"dfa8425bbc2d","msg":"Back-end is running at http://localhost:3100 in production mode. Press CTRL-C to stop"}
growthbook_1  | (node:65) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
growthbook_1  | 
growthbook_1  | Please migrate your code to use AWS SDK for JavaScript (v3).
growthbook_1  | For more information, check the migration guide at https://a.co/7PzMCcy
growthbook_1  | {"level":40,"time":1712283978970,"pid":65,"hostname":"dfa8425bbc2d","err":{"type":"MongooseServerSelectionError","message":"connect ECONNREFUSED 127.0.0.1:27017","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at Connection.openUri (/usr/local/src/app/node_modules/mongoose/lib/connection.js:825:32)\n    at /usr/local/src/app/node_modules/mongoose/lib/index.js:414:10\n    at /usr/local/src/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5\n    at Promise._execute (/usr/local/src/app/node_modules/bluebird/js/release/debuggability.js:384:9)\n    at Promise._resolveFromExecutor (/usr/local/src/app/node_modules/bluebird/js/release/promise.js:518:18)\n    at new Promise (/usr/local/src/app/node_modules/bluebird/js/release/promise.js:103:10)\n    at promiseOrCallback (/usr/local/src/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)\n    at Mongoose._promiseOrCallback (/usr/local/src/app/node_modules/mongoose/lib/index.js:1290:10)\n    at Mongoose.connect (/usr/local/src/app/node_modules/mongoose/lib/index.js:413:20)\n    at /usr/local/src/app/packages/back-end/dist/init/mongo.js:34:34\n    at Generator.next (<anonymous>)\n    at /usr/local/src/app/packages/back-end/dist/init/mongo.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/local/src/app/packages/back-end/dist/init/mongo.js:4:12)\n    at exports.default (/usr/local/src/app/packages/back-end/dist/init/mongo.js:21:25)\n    at /usr/local/src/app/packages/back-end/dist/init/index.js:25:43","reason":{"type":"Unknown","servers":{},"stale":false,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"setName":null,"maxElectionId":null,"maxSetVersion":null,"commonWireVersion":0,"logicalSessionTimeoutMinutes":null}},"msg":"Failed to connect to MongoDB. Retrying with field remapping for mongodb v3 to v4"}

growthbook_1  | {"level":50,"time":1712284008979,"pid":65,"hostname":"dfa8425bbc2d","err":{"type":"MongooseServerSelectionError","message":"connect ECONNREFUSED 127.0.0.1:27017","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at Connection.openUri (/usr/local/src/app/node_modules/mongoose/lib/connection.js:825:32)\n    at /usr/local/src/app/node_modules/mongoose/lib/index.js:414:10\n    at /usr/local/src/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5\n    at Promise._execute (/usr/local/src/app/node_modules/bluebird/js/release/debuggability.js:384:9)\n    at Promise._resolveFromExecutor (/usr/local/src/app/node_modules/bluebird/js/release/promise.js:518:18)\n    at new Promise (/usr/local/src/app/node_modules/bluebird/js/release/promise.js:103:10)\n    at promiseOrCallback (/usr/local/src/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)\n    at Mongoose._promiseOrCallback (/usr/local/src/app/node_modules/mongoose/lib/index.js:1290:10)\n    at Mongoose.connect (/usr/local/src/app/node_modules/mongoose/lib/index.js:413:20)\n    at /usr/local/src/app/packages/back-end/dist/init/mongo.js:50:38\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/local/src/app/packages/back-end/dist/init/mongo.js:6:65)","reason":{"type":"Unknown","servers":{},"stale":false,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"setName":null,"maxElectionId":null,"maxSetVersion":null,"commonWireVersion":0,"logicalSessionTimeoutMinutes":null}},"msg":"Failed to connect to MongoDB after retrying"}
growthbook_1  | {"level":50,"time":1712284008981,"pid":65,"hostname":"dfa8425bbc2d","err":{"type":"Error","message":"MongoDB connection error.","stack":"Error: MongoDB connection error.\n    at /usr/local/src/app/packages/back-end/dist/init/mongo.js:54:19\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/local/src/app/packages/back-end/dist/init/mongo.js:6:65)"},"msg":"Failed to initialize application"}
growthbook_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
growthbook_1  | error Command failed with exit code 1.
growthbook_1  | `yarn start` failed with exit code 1

**Comment by Auz** [comment] 2024-04-05 06:30
Hi Jiancong - this is not a bug with the code, this is a problem with your setup and not providing the correct URL for mongoDB (127.0.0.1 is not routable outside your docker container). I'm going to close this issue, but if you're looking for support, please join our slack channel: slack.growthbook.io

**Closed by Auz** 2024-04-05 06:30 UTC
Labels: bug
