### ISSUE TITLE
[Bug] Getting 400 error "Bad request" when adding capping to the metric

### ISSUE THREAD

**Issue by ndubitsk** [growthbook/growthbook#2052] opened 2024-01-19 10:23 UTC
### Summary

When we add capping to the metric, we get 400 error when we calculate results of the experiment.

#### Expected Behavior

Metric is correctly calculated.

#### Current Behavior

Metric is not calculated – we get 400 error.

**Comment by lukesonnet** [comment] 2024-01-24 22:31
Can you share any more context? I'm afraid I can't replicate this error and capping seems to be working fine. I'm going to close this for now, but please feel free to reopen it if you can reproduce it and share any more information about the error.

**Closed by lukesonnet** 2024-01-24 22:31 UTC
Labels: bug
