### ISSUE TITLE
[Feature] Cancel Queries in Snowflake from GrowthBook

### ISSUE THREAD

**Issue by juliannaharwood** [growthbook/growthbook#1091] opened 2023-03-20 18:00 UTC
### Description of Feature

The desired state is when a user cancels an in-progress data refresh in GrowthBook, it also cancels the Snowflake queries that were started. Currently, cancelling in GrowthBook only stops the UI from updating. A user needs to manually cancel all of the Snowflake queries in order to actually stop them from running.

**Comment by lukesonnet** [comment] 2023-10-17 22:00
We agree this could be improved. Closing as a duplicate of #310

**Closed by lukesonnet** 2023-10-17 22:00 UTC
Labels: enhancement
