### ISSUE TITLE
[Bug] Experiments created from Features have a silently unset Assignment Table

### ISSUE THREAD

**Issue by bosyk** [growthbook/growthbook#2105] opened 2024-02-08 16:15 UTC
### Summary

When an Experiment is created from the Feature's experiment rule, the assignment table of the corresponding experiment is silently non-configured. This confuses users. Observed up to the build aa0207f.

#### Expected Behavior

When an Experiment is created from the Feature's experiment rule, then either of both applies:
* The assignment table is selected correctly according to the rule's assignment attribute.
* The user gets informed that the experiment assignment table needs to be set consistently by hand.

#### Current Behavior

When an Experiment is created from the Feature's experiment rule, the assignment table of the corresponding experiment is silently non-configured.

The Analysis Settings from the experiment look like this:
![image](https://github.com/growthbook/growthbook/assets/30110352/2a032cdc-b099-4e2b-b455-0a0550da21d5)

A click on the button "Update" shows the following error
![image](https://github.com/growthbook/growthbook/assets/30110352/aa328590-7559-45f3-a8eb-db5b1a871be0)

This might be the expected behaviour. However, it feels like a bug, since it's first noticeable when the error in the latter screenshot is shown.

**Comment by lukesonnet** [comment] 2024-02-12 15:18
We agree that this flow is sub-optimal and have had a few discussions about how to fix it. Closing it as a duplicate of both #1943 and #1812 .

**Closed by lukesonnet** 2024-02-12 15:18 UTC
Labels: bug
