### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kennethalston** [growthbook/growthbook#2737] opened 2024-07-12 18:39 UTC
### Summary

It appears that the `Chance to Win` percentage in the UI is not being correctly calculated. 

#### Expected Behavior

I believe this is usually calculated something like as 1 - computed p-value

#### Current Behavior

but currently, best I can tell, it's returning the straight p-value.  

So for example, in an experiment setup I have now, it's indicating a metric "won" because of a 96.2% chance of winning; however, that seemed questionable based on my data, so I computed significance manually, and got a p-value of 0.9682, which suggests a lot of uncertainty at this stage

**Comment by lukesonnet** [comment] 2024-07-12 18:41
Can you share a screen shot? Our Bayesian engine does not compute p-values at all. It's a entirely different statistics engine.

**Comment by kennethalston** [comment] 2024-07-12 18:48
@lukesonnet here's a screen shot.  I'm curious if these are the expected results.  In both cases, the chance to win is pretty far from significant and happened to align with p-values, so I had assumed that was the issue

![image](https://github.com/user-attachments/assets/e856d899-8a55-478f-826e-01f7ef878381)

**Comment by lukesonnet** [comment] 2024-07-12 21:45
Yes, this seems correct.

Let's compute the p-value by hand to sanity check the bayesian result

Manual p-value computation
control mean: `0.0315`
control variance: `0.0315 * ( 1-0.0315 ) = 0.0216`

treatment mean: `0.0357`
treatment variance: `0.0357 * ( 1-0.0357 ) = 0.0230`


lift: `(0.0357 - 0.0315) / 0.0315 = 0.133` (approx 0.132, which is the 13.2% in the UI; difference is just due to rounding error here in my math)
lift stddev: `sqrt[ (0.0216 * 0.0357^2) / (0.0315^4 * 13500) + (0.0230) / (0.0315^2 * 13300) ] = 0.0618`

So `0.133/0.0618 = 2.15` is our z-statistic, which is somewhere between 0.01 and 0.05 as a p-value.

So that chance to win result is reasonable, but a bit harder to do on the back of a napkin.

Closing this as it is not a bug.

You can read more about our statistics here: https://docs.growthbook.io/statistics/overview  and https://docs.growthbook.io/statistics/details.

And you can read more about interpreting these results here: https://docs.growthbook.io/app/experiment-results

**Closed by lukesonnet** 2024-07-12 21:45 UTC
Labels: bug
