### ISSUE TITLE
"Create New Draft" in "Add Experiment" dialog doesn't go anywhere

### ISSUE THREAD

**Issue by fastfedora** [growthbook/growthbook#330] opened 2022-05-03 00:25 UTC
When I click the "Create New Draft" link in the "Add Experiment" dialog, the page refreshes and shows me the list of all experiments again. No blank experiment creation dialog or page is ever shown.

![image](https://user-images.githubusercontent.com/1173892/166346301-af8fda9d-d2d1-4d94-9802-10277fb2f2c1.png)

**Comment by jdorn** [comment] 2022-05-03 00:37
That was caused by the same PR that was merged a couple days ago.  I'm pushing up a fix now

**Closed** 2022-05-03 00:42 UTC
